version: '3.9'
services:
  valheim:
    image: lloesche/valheim-server
    volumes:
      - E:\valheim-server\config:/config
      - E:\valheim-server\data:/opt/valheim
    ports:
      - '2456-2458:2456-2458/udp'
    environment:
      - SERVER_NAME=Sons of Olaf
      - SERVER_PASS=potato
      - SERVER_PUBLIC=1
      - WORLD_NAME=VikingsHo
